- hosts: server
  tasks:
          - name: "install httpd server"
            package: 
              name: httpd
              state: present


          - name: "copying the files"
            copy:
              src: "index.html"
              dest: "/var/www/html"


          - name: "starting the webserver"
            service: 
              name: httpd
              state: started
